name: Code Coverage

on:
  workflow_dispatch

jobs:
  codecov:
    runs-on: macos-latest

    steps:
      - name: Delete .NET
        run: sudo rm -rf /usr/share/dotnet
      - name: Set environment variable
        run: export ADB_INSTALL_TIMEOUT=20
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          sdcard-path-or-size: 5000M
          ram-size: 4000M
          script: ./gradlew jacocoTestReport connectedCheck
